# Dependencies
markdown:         redcarpet
highighter:       true




# Permalinks
permalink:        /blog/:title

# Setup
title:            Carrie Jackson
tagline:          "I'm a a web designer & maker"
description:      'Life can be really tough and confusing at times. This site is here to help you navigate through your teenage years.'
url:              http://carrie.mojaworks.co.uk

author:
  name:           'Carrie Jackson'
  url:            http://carrie.mojaworks.co.uk

paginate:         10


# Custom vars
version:          1.0.0

github:
  repo:           ''
baseurl:          ''